#!/usr/bin/env bash
# GNU bash, version 4.3.8(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# TODO: Check out xdokey to translate special characters into xkeysym strings

words="$1"

if [[ -z "$words" ]]; then
  echo "$words"
  while read words; do
    while test -n "$words"; do
      c=${words:0:1}     # Get the first character
      xdotool --clearmodifiers --delay 25 key $c
      words=${words:1}   # trim the first character
    done
  done
else
  while [[ -n "$words" ]]; do
    c=${words:0:1}     # Get the first character
    xdotool --clearmodifiers --delay 25 key $c
    words=${words:1}   # trim the first character
  done
fi

