#!/usr/bin/env bash
# GNU bash, version 4.3.8(1)-release (x86_64-unknown-linux-gnu)
#
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#
# TODO: Check out xdokey to translate special characters into xkeysym strings

while read "$line"; do
  xdotool type "$line"
done

# vim: ft=sh :
